/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsGeneratorsIdentifiersRouteImport } from './routes/tools/generators/identifiers'
import { Route as ToolsEncodersBase64RouteImport } from './routes/tools/encoders/base64'
import { Route as ToolsConvertersDatetimeRouteImport } from './routes/tools/converters/datetime'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGeneratorsIdentifiersRoute =
  ToolsGeneratorsIdentifiersRouteImport.update({
    id: '/tools/generators/identifiers',
    path: '/tools/generators/identifiers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsEncodersBase64Route = ToolsEncodersBase64RouteImport.update({
  id: '/tools/encoders/base64',
  path: '/tools/encoders/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsConvertersDatetimeRoute = ToolsConvertersDatetimeRouteImport.update({
  id: '/tools/converters/datetime',
  path: '/tools/converters/datetime',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/converters/datetime': typeof ToolsConvertersDatetimeRoute
  '/tools/encoders/base64': typeof ToolsEncodersBase64Route
  '/tools/generators/identifiers': typeof ToolsGeneratorsIdentifiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/converters/datetime': typeof ToolsConvertersDatetimeRoute
  '/tools/encoders/base64': typeof ToolsEncodersBase64Route
  '/tools/generators/identifiers': typeof ToolsGeneratorsIdentifiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/converters/datetime': typeof ToolsConvertersDatetimeRoute
  '/tools/encoders/base64': typeof ToolsEncodersBase64Route
  '/tools/generators/identifiers': typeof ToolsGeneratorsIdentifiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/converters/datetime'
    | '/tools/encoders/base64'
    | '/tools/generators/identifiers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/converters/datetime'
    | '/tools/encoders/base64'
    | '/tools/generators/identifiers'
  id:
    | '__root__'
    | '/'
    | '/tools/converters/datetime'
    | '/tools/encoders/base64'
    | '/tools/generators/identifiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsConvertersDatetimeRoute: typeof ToolsConvertersDatetimeRoute
  ToolsEncodersBase64Route: typeof ToolsEncodersBase64Route
  ToolsGeneratorsIdentifiersRoute: typeof ToolsGeneratorsIdentifiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/generators/identifiers': {
      id: '/tools/generators/identifiers'
      path: '/tools/generators/identifiers'
      fullPath: '/tools/generators/identifiers'
      preLoaderRoute: typeof ToolsGeneratorsIdentifiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/encoders/base64': {
      id: '/tools/encoders/base64'
      path: '/tools/encoders/base64'
      fullPath: '/tools/encoders/base64'
      preLoaderRoute: typeof ToolsEncodersBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/converters/datetime': {
      id: '/tools/converters/datetime'
      path: '/tools/converters/datetime'
      fullPath: '/tools/converters/datetime'
      preLoaderRoute: typeof ToolsConvertersDatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsConvertersDatetimeRoute: ToolsConvertersDatetimeRoute,
  ToolsEncodersBase64Route: ToolsEncodersBase64Route,
  ToolsGeneratorsIdentifiersRoute: ToolsGeneratorsIdentifiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
